# Generated by Django 2.1.2 on 2018-10-30 20:09

import aplicacion.modelFunctions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=30)),
                ('horario', models.CharField(default='MATUTINO', max_length=30)),
                ('precio', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('birthdate', models.DateField(blank=True, default='2000-01-01')),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/no-image.jpg', upload_to=aplicacion.modelFunctions.upload_profile_pic_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rating', models.IntegerField(blank=True, null=True)),
                ('teacher_rating', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Profile'),
        ),
    ]
