# Generated by Django 2.1.2 on 2018-11-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('is_teacher', 'Teacher permissions'),)},
        ),
    ]
