# Generated by Django 2.1.2 on 2018-11-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20181105_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
        migrations.AddField(
            model_name='take',
            name='aceptada',
            field=models.BooleanField(default=False),
        ),
    ]
