# Generated by Django 2.1.1 on 2018-11-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20181105_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='take',
            name='terminada',
            field=models.BooleanField(default=False),
        ),
    ]
