# Generated by Django 2.1 on 2018-10-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_profile_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='take',
            name='student_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='take',
            name='teacher_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
