# Generated by Django 2.1.2 on 2018-10-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_auto_20181014_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='horario',
            field=models.CharField(default='MATUTINO', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
